/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TiffinPlan = IDL.Variant({
  'custom' : IDL.Null,
  'monthly' : IDL.Null,
  'corporate' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Time = IDL.Int;
export const Enquiry = IDL.Record({
  'name' : IDL.Text,
  'plan' : TiffinPlan,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, TiffinPlan],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TiffinPlan = IDL.Variant({
    'custom' : IDL.Null,
    'monthly' : IDL.Null,
    'corporate' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Time = IDL.Int;
  const Enquiry = IDL.Record({
    'name' : IDL.Text,
    'plan' : TiffinPlan,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, TiffinPlan],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };